### ISSUE TITLE
environment.yaml can be improved

### ISSUE THREAD

**Issue by YouJiacheng** [isl-org/MiDaS#231]
[nvidia::cudatoolkit=11.7](https://anaconda.org/nvidia/cudatoolkit) does NOT exist on win-64. There is only `11.5`.
So `conda env create -f environment.yaml` will fail on Windows.
This may be resolved by using `conda-forge::conda-forge::cudatoolkit=11.7` instead:
```yaml
name: midas-py310
channels:
  - pytorch
  - defaults
dependencies:
  - conda-forge::cudatoolkit=11.7
  - python=3.10.8
  - pytorch=1.13.0
  - torchvision=0.14.0
  - pip=22.3.1
  - numpy=1.23.4
  - pip:
    - opencv-python==4.6.0.66
    - imutils==0.5.4
    - timm==0.6.12
    - einops==0.6.0
```
Or we can follow [PyTorch Start Locally](https://pytorch.org/get-started/locally/) (`conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`) to use `pytorch-cuda=11.7` and add `nvidia` into channels. (Before `1.13`, they use `conda-forge::cudatoolkit`, i.e. `conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge`)
```yaml
name: midas-py310
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.8
  - pytorch=1.13.0
  - torchvision=0.14.0
  - pytorch-cuda=11.7
  - pip=22.3.1
  - numpy=1.23.4
  - pip:
    - opencv-python==4.6.0.66
    - imutils==0.5.4
    - timm==0.6.12
    - einops==0.6.0
```
